Improve/use vote counts stored in model
MauriceNaftalin/voteroid pull request #4
Opened 2024-02-20 09:29 UTC by MauriceNaftalin

2024-02-21 17:32 UTC, lifey requested changes

2024-02-21 17:32 UTC, lifey commented on src/main/java/com/voteroid/messagingstompwebsocket/PresentationController.java
> +}
github is annoyed when a file is not terminated with a \n

2024-02-21 17:32 UTC, lifey commented on src/main/java/com/voteroid/messagingstompwebsocket/PresentationController.java
> +/*
As you have full history no need to comment out old code

2024-02-21 17:32 UTC, lifey commented on examples/presentation-local.adoc
> +<div id="question1">No connection to server</div>
this is replaced with content ? so it is like alt-text ?

2024-02-21 17:32 UTC, lifey commented on src/main/resources/static/iframeStompManager.js
> +        setBarHeight(JSON.parse(voteUpdate.body).content);
much better 👍

2024-02-22 14:40 UTC, MauriceNaftalin commented on src/main/java/com/voteroid/messagingstompwebsocket/PresentationController.java
> +}
👍

2024-02-22 14:41 UTC, MauriceNaftalin commented on src/main/java/com/voteroid/messagingstompwebsocket/PresentationController.java
> +/*
👍

2024-02-22 14:42 UTC, MauriceNaftalin commented on examples/presentation-local.adoc
> +<div id="question1">No connection to server</div>
If the presentation is opened without a server running, this is the text that appears in place of the iframe. Once the server is running (and the page is refreshed), the iframe appears instead.

2024-02-22 14:43 UTC, MauriceNaftalin commented on src/main/resources/static/iframeStompManager.js
> +        setBarHeight(JSON.parse(voteUpdate.body).content);
😀

2024-02-22 18:41 UTC, lifey approved these changes

2024-02-22 23:10 UTC, merged